version: 0.0
os: linux 

files:
  - source: bin
    destination: /opt/hello

permissions:
  - object: /opt/hello
    pattern: "**"
    owner: root
    group: root
    mode: 555
    type:
      - file

