version: 0.1
os: linux 

files:
  - source: /
    destination: /opt/hello

permissions:
  - object: /opt/hello
    pattern: "**"
    owner: root
    group: root
    mode: 555
    type:
      - file

hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 20
      runas: root
  ApplicationStart:
    - location: start.sh
      timeout: 20
      runas: root

