version: 0.2

phases:
  pre_build:
    commands:
      - apt-get -q update -y
      - apt-get -q install -y build-essential curl zip
      - apt-get -q install -y apt-transport-https ca-certificates software-properties-common

      - curl https://storage.googleapis.com/golang/go1.8.linux-amd64.tar.gz | tar -xz -C /usr/local
      - GOROOT=/usr/local/go
      - GOPATH=/opt/go
      - PATH=$PATH:$GOROOT/bin:$GOPATH/bin
      - go version

      - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      - apt-key fingerprint 0EBFCD88
      - sudo apt-get install docker-ce
      - docker version

  build:
    commands:
      - make clean build package

  post_build:
    commands:
      - make publish

artifacts:
  files:
    - appspec.yml
    - bin/*
    - scripts/*
  discard-paths: no