version: 0.2

phases:
  pre_build:
    commands:
      - service docker start
      - make --version
      - go version
      - aws --version


  build:
    commands:
      - make V=1 clean build package publish

artifacts:
  files:
    - appspec.yml
    - bin/*
    - scripts/*
  discard-paths: no