version: 0.2

phases:
  pre_build:
    commands:
      - service docker start

  build:
    commands:
      - make V=1 clean build package

  post_build:
    commands:
      - make V=1 publish

artifacts:
  files:
    - appspec.yml
    - bin/*
    - scripts/*
  discard-paths: no