version: 0.2

phases:
  pre_build:
    commands:
      - make clean

  build:
    commands:
      - make build package

  post_build:
    commands:
      - make publish

artifacts:
  files:
    - appspec.yml
    - bin/*
    - scripts/*
  discard-paths: no